### ISSUE TITLE
The issues grid throws exception on sort

### ISSUE THREAD

**Issue by matanasov** [telerik/blazor-dashboard#1]
1. Open the app here:
https://demos.telerik.com/blazor-dashboard-app/

2. Go to Issues tab.
3. Sort by `Labels` or `Details`

**Comment by marin-bratanov** [comment]
Depends on [https://feedback.telerik.com/blazor/1408645-ability-to-set-sortable-for-individual-columns](https://feedback.telerik.com/blazor/1408645-ability-to-set-sortable-for-individual-columns) so we can disable sorting for the Labels and Details columns where the error arises - their bound fields are not sortable in the underlying model, and they can't really be, so sorting needs to be disabled for them. Alternatively, some dummy sort method can be implemented for them.

**Comment by KevinFarrow** [comment]
Will this ever be fixed?

**Comment by marin-bratanov** [comment]
Hi Kevin,

It will be fixed when the grid gains the ability to disable sorting per columns. You can Follow and Vote on [the item](https://feedback.telerik.com/blazor/1408645-ability-to-set-sortable-for-individual-columns) to get status notifications via email.

Alternatively, `IComparable` can be implemented in the model to actually allow sorting. You can see an example in the following page: [https://feedback.telerik.com/blazor/1408650-column-sorting-breaks-under-subclassing-scenarios](https://feedback.telerik.com/blazor/1408650-column-sorting-breaks-under-subclassing-scenarios)

**Comment by marin-bratanov** [comment]
While the feature in the grid that would have fixed this is not implemented (please Follow it in the portal), I am closing this because the grid does not exhibit this problem after the last design update - the columns in the grid all all primitive types now and sorting works out-of-the-box.
