### ISSUE TITLE
Material theme

### ISSUE THREAD

**Issue by drinkwater99** [telerik/blazor-dashboard#4]
Is there any version of this app using the Material theme?
If not, how would you go about applying the Material theme ?

**Comment by marin-bratanov** [comment]
One of the goals of this app is to showcase the Bootstrap theme integration with Bootstrap so we don't have a Material theme version. Nevertheless, you can integrate it yourself based on how the app is implemented.

You should first extract the styling of the app for its own layout. At the moment it is SASS ([file](https://github.com/telerik/blazor-dashboard/blob/master/BlazorDashboard/sass/_layout.scss), which depends on the adjacent variables file).

Then, remove the Kendo Bootstrap Theme dependency ( [link](https://github.com/telerik/blazor-dashboard/blob/master/BlazorDashboard/package.json#L12) ). In fact, this makes most of the [SASS build infrastructure](https://github.com/telerik/blazor-dashboard/blob/master/BlazorDashboard/gulpfile.js) unnecessary (and probably also the entire npm dependency), so you can consider dropping the rest of the dependencies (maybe after you have compiled the SASS once to get the layout stylesheet in human-readable form in case you don't want to edit the SCSS to CSS manually). This depends on how you prefer to include Bootstrap itself - at the moment it comes from npm so we can get its SASS version and compile it with the variables from this app, but with the Material theme this is no longer applicable, so you can just include it in any preferred way (perhaps without npm to make the app more lightweight).

> you still need bootstrap for the layouts, they rely on classes from it

Then, add the Material theme as usual: [https://docs.telerik.com/blazor-ui/themes/overview](https://docs.telerik.com/blazor-ui/themes/overview)

**Comment by marin-bratanov** [comment]
Hi,
I hope you have managed to get this done. If so, feel free to post here a link to a repo with it.
If not, what are the issues you are facing?

**Comment by dwbeva** [comment]
No I haven't had a chance to attempt it. Thanks for the follow-up.

**Comment by marin-bratanov** [comment]
It's been a while without new information or problems about this, so I am going to close it. If issues in the app or the components manifest, feel free to reopen this.
